addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip]
    target_paths: 4c355684-4ca7-4866-b00d-b0512f639e2c
after_success: mvn cobertura:cobertura coveralls:report
jdk: [oraclejdk7]
language: java
script: mvn clean verify;./df-build.sh;./df-build.sh;mvn test jacoco:report coveralls:report
sudo: false
# Modified by Insights Service at 2016-03-01 15:26:47.592780
